# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f395fdaf542392c232f99e7688081a13eca873556f70fe9a9ab0391de21711e44e228b26529ab984b11da42fcea55618673a36e37dfc0c197b76249fe8ed8ab

test:
  secret_key_base: 50748a0603aea6ba8e00c638b097cae815118e28fdadcc56cb96098fb701d7e2aa8cc2fbc8355a6b47bb12d97fd7fa4f38ac36e217842d944d9583c8a74d6a40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
